export const ActionTypes = {
  // SET_POSTS: "SET_POSTS",
  ADD_USER: "ADD_USER",
  INCREASE_SAVINGS: "INCREASE_SAVINGS",
  // SELECTED_POST: "SELECTED_POST",
  // REMOVE_SELECTED_POST: "REMOVE_SELECTED_POST",
  // EDIT_POST: "EDIT_POST"
}