export const ActionTypes = {
  // SET_POSTS: "SET_POSTS",
  ADD_USER: "ADD_USER",
  // DELETE_POST: "DELETE_POST",
  // SELECTED_POST: "SELECTED_POST",
  // REMOVE_SELECTED_POST: "REMOVE_SELECTED_POST",
  // EDIT_POST: "EDIT_POST"
}